<?php

/**
 * @file
 * Contains learnd8.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function learnd8_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the learnd8 module.
    case 'help.page.learnd8':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for learning D8') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function learnd8_theme() {
  return [
    'learnd8' => [
      'render element' => 'children',
    ],
  ];
}
